spring:
  application:
    name: payments-api
  mvc:
    async:
      request-timeout: 30s
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        "[enable.idempotence]": true
        "[spring.json.add.type.headers]": false
        "[max.block.ms]": 5000
        "[request.timeout.ms]": 5000
        "[delivery.timeout.ms]": 15000

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

app:
  kafka:
    topics:
      pagamentos-solicitados: pagamentos.solicitados
